export const assets = {
  Sider: require("./img/5.jpeg"),
  LoginBG: require("./img/loginbg.jpg"),
  First: require("./img/first.jpg"),
  Second: require("./img/second.png"),
  Third: require("./img/third.png"),
  Fourth: require("./img/fourth.png"),
  Background:require("./img/Picture19.jpg"),
  Background2:require("./img/Picture19rotate.jpg"),
  Fifth:require("./img/Dashboardsubsitute.jpg"),
  Sixth:require("./img/Picture21.png"),
  Seventh:require("./img/Picture22.png"),
  Eight:require("./img/Picture23.png"),
  LoginPage: require("./img/login_page.png"),
  logo: require("./img/logo.png"),
  profileImage: require("./img/profile_image.jpg"),
  coverImage: require("./img/cover.png"),
  profileDp: require("./img/profile_dp.jpg"),
  createworkspaceform: require("./img/create-workspace-form.jpg"),
  startworkspace: require("./img/start-workspace-image.jpg"),
  findworkspace: require("./img/find_workspace_image.jpg"),
  loginImage: require("./img/login_image.png"),
  signupImage: require("./img/signup_image.png"),
  otpGIF: require("./gif/otp.gif"),
  loginGIF: require("./gif/login.gif"),
  signupGIF: require("./gif/signup.gif"),
  forgetPasswordGIF: require("./gif/forgetpassword.gif"),
  resetPasswordGIF: require("./gif/resetpassword.gif"),
  emptyPageGIF: require("./gif/emptychat.gif"),
  upload: require("./icons/upload-to-cloud.png"),
  thumbnail: require("./img/thumbnail.jpg"),
  modalBackground: require("./img/modal.png")
};
